### ISSUE TITLE
Add battle rules clause

### ISSUE THREAD

**Issue by ghost** [randombyte-developer/poke-battle-clauses#2]
Can merge other clause
like
https://pastebin.com/5biGQuRY

**Comment by GsPio** [comment]
> Can merge other clause
> like
> `clause { 
          list=[ Mega, OHKO, Bag, ] list-type=merge }`

**Comment by randombyte-developer** [comment]
So you want something that requires multiple rules to pass?

**Comment by ghost** [comment]
yes

**Comment by randombyte-developer** [comment]
I can't test it right now, but what happens when you put multiple clauses in the clause list in the trainer editor GUI? Is it like an OR thing, or and AND thing?

**Comment by randombyte-developer** [comment]
Closed due to inactivity
